ALTER TABLE `Usuario` ADD `dsSenhaSalt` VARCHAR(200) NOT NULL AFTER `dsSenha`;

ALTER TABLE `Usuario` CHANGE `dsSenha` `dsSenha` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL;